profile_list:
  - display_name: "HASS Notebook"
    description: A Jupyter Notebook server with Python kernel and various HASS packages pre-installed.
    default: false
    kubespawner_override:
      image_spec: hub.bccvl.org.au/tinker/jupyter-hass-notebook:latest
  - display_name: "RStudio Notebook"
    description: A Jupyter Notebook server with R kernel and various R packages including RStudio pre-installed.
    default: false
    kubespawner_override:
      image_spec: hub.bccvl.org.au/jupyter/r-notebook:0.9.4
